language: nix
arch: arm64
os: bionic

cache:
  directories:
  - $HOME/nix.store

addons:
  apt:
    packages:
    - build-essential
    - help2man
    - autoconf

# https://nixos.wiki/wiki/Nix_on_Travis
# before_install:
# - sudo mkdir -p /etc/nix
# - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
# - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

# before_cache:
# - mkdir -p $HOME/nix.store
# - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

# before_script:
# - sudo mkdir /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
